services:
  stats-server:
    build:
      context: ./ewm-statistic/ewm-server
      dockerfile: Dockerfile
    image: java-explore-with-me-statistics
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/statistics-db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  ewm-service:
    image: postgres:16.1
    container_name: ewm-service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: statistics-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      timeout: 5s
      interval: 5s
      retries: 10
